# Generated by Django 3.0.5 on 2021-05-14 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('long', models.CharField(max_length=1000)),
                ('short', models.CharField(max_length=10)),
                ('time_to_delete', models.IntegerField(default=800)),
            ],
        ),
    ]
