# Generated by Django 3.0.5 on 2021-05-16 00:45

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('long', models.CharField(default='', max_length=1000)),
                ('short', models.CharField(default='', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_at', models.IntegerField(default=1621126211627)),
            ],
        ),
    ]
