# Generated by Django 3.0.5 on 2021-05-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturl', '0004_auto_20210519_0341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='times_redirected',
            new_name='redirect_number',
        ),
        migrations.AlterField(
            model_name='url',
            name='expire_at',
            field=models.IntegerField(default=1621396948709),
        ),
    ]
